// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdRLx9lMJ5sTyh7c8yUmOPpXiOmg4O-BE',
    appId: '1:186787641697:web:90b83f0abba8ae0306ad20',
    messagingSenderId: '186787641697',
    projectId: 'fl-tiffen-wala',
    authDomain: 'fl-tiffen-wala.firebaseapp.com',
    storageBucket: 'fl-tiffen-wala.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2hVAG96szDI7_KCeKGwKlevRUfROqMEE',
    appId: '1:186787641697:android:86ac6c9c17afcff306ad20',
    messagingSenderId: '186787641697',
    projectId: 'fl-tiffen-wala',
    storageBucket: 'fl-tiffen-wala.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChFLUMU_i9kApQT7GGJUz9ExxCCKhTBak',
    appId: '1:186787641697:ios:f0289e2a56faa48d06ad20',
    messagingSenderId: '186787641697',
    projectId: 'fl-tiffen-wala',
    storageBucket: 'fl-tiffen-wala.appspot.com',
    iosBundleId: 'com.qwerty.tiffenWala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChFLUMU_i9kApQT7GGJUz9ExxCCKhTBak',
    appId: '1:186787641697:ios:edc6f0803c6e393b06ad20',
    messagingSenderId: '186787641697',
    projectId: 'fl-tiffen-wala',
    storageBucket: 'fl-tiffen-wala.appspot.com',
    iosBundleId: 'com.qwerty.tiffenWala.RunnerTests',
  );
}
